### ISSUE TITLE
Threads not stopped automatically

### ISSUE THREAD

**Issue by codeblooded1729** [iden3/snarkjs#370] opened 2023-05-16 11:55 UTC
I have observed that `snarkjs.groth16.prove()` and `snarkjs.groth16.verify()` do not, by default, terminate the threads spawned by stuff like `buildBn128()` which is called internally. But looks like all that needs to be done is call `curve.terminate()` after the job of curve is done. Is there any other solution provided by the library.

**Comment by phated** [comment] 2023-05-18 03:58
Duplicate of #152 - this is by design.

**Closed by phated** 2023-05-18 03:58 UTC
