### ISSUE TITLE
Error on Plonk call data generation

### ISSUE THREAD

**Issue by skardas** [iden3/snarkjs#149] opened 2022-05-22 12:59 UTC
If you look at the link:
https://github.com/iden3/snarkjs/blob/31f7867fa031c7e2c056331a7a3d4c6c29d5de35/build/cli.cjs#L7759

you will see:

 const pub = unstringifyBigInts$1(_proof);
    const proof = unstringifyBigInts$1(_pub);

this is wrong so we get error, you can fix it as follows:

 const **pub** = unstringifyBigInts$1(**_pub**);
    const **proof** = unstringifyBigInts$1(**_proof**);

**Comment by skardas** [comment] 2022-05-22 14:09
similar error is here

https://github.com/iden3/snarkjs/blob/31f7867fa031c7e2c056331a7a3d4c6c29d5de35/build/cli.cjs#L6002

**Comment by phated** [comment] 2022-05-22 21:39
Duplicate of #148 - want to submit a PR?

**Closed** 2022-05-23 19:49 UTC
